Add basic delivery tests

diff --git a/debian/mailrobots.postinst b/debian/mailrobots.postinst
--- a/debian/mailrobots.postinst
+++ b/debian/mailrobots.postinst
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # postinst script for mailrobots
 #
 # see: dh_installdeb(1)
@@ -17,10 +17,46 @@ set -e
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+configure_exim() {
+    invoke-rc.d exim4 stop
+
+    install -m 0644 -t /etc/exim4 /usr/lib/mailrobots/update-exim4.conf.conf
+    # XXX /etc/mailname currently contains bare hostname
+
+    # exim's init script fails if exim can't be started
+    if ! invoke-rc.d exim4 start; then
+        systemctl status exim4
+        exit 1
+    fi
+}
+
+configure_dovecot() {
+    invoke-rc.d dovecot stop
+
+    sed \
+        -e "s/@first_valid_uid@/$(id -u mailstorage)/g" \
+        -e "s/@last_valid_uid@/$(id -g mailstorage)/g" \
+        -e "s/@first_valid_gid@/$(id -u mailstorage)/g" \
+        -e "s/@last_valid_gid@/$(id -g mailstorage)/g" \
+        -e "s/@mailname@/$(</etc/mailname)/g" \
+        /usr/lib/mailrobots/dovecot-local.conf.in \
+        > /etc/dovecot/local.conf
+
+    # dovecot's systemd unit does not use readiness notification
+    invoke-rc.d dovecot start
+    sleep 1
+    if ! invoke-rc.d dovecot status > /dev/null; then
+        systemctl status dovecot
+        exit 1
+    fi
+}
 
 case "$1" in
     configure)
         systemd-sysusers /usr/lib/sysusers.d/mailrobots.conf
+
+        configure_exim
+        configure_dovecot
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
